import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-6 py-4 bg-white border-b mb-6">
          <div className="font-bold text-lg">Medium Website</div>
          <ul className="flex gap-6">
            <li>
              <a href="/" className="hover:underline">Home</a>
            </li>
            <li>
              <a href="/signin" className="hover:underline">Sign In</a>
            </li>
            <li>
              <a href="/signup" className="hover:underline">Sign Up</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
