import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <nav className="w-full flex items-center justify-between px-6 py-4 bg-white border-b mb-6">
          <div className="font-bold text-lg">Medium Website</div>
          <ul className="flex gap-6">
            <li>
              <a href="/" className="hover:underline">Home</a>
            </li>
            <li>
              <a href="/auth/signin" className="hover:underline">Sign In</a>
            </li>
            <li>
              <a href="/auth/signup" className="hover:underline">Sign Up</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
